# 全局异常处理
zeta-kotlin项目提供了两个自定义异常`ArgumentException(参数异常)`、`BusinessException(业务异常)`。

它们分别用于请求参数校验出错，业务执行出错的时候。

使用方式很简单，手动抛出一个异常：
```kotlin
throw BusinessException("因为xxx原因，业务进行不下去了，请管理员检查")
```
手动抛出的异常会被全局异常处理器拦截并处理自动将异常转换成一个请求失败的返回值。



## 定义一个自定义的异常

很多时候，仅仅靠本项目提供的这两个自定义异常是远远不够的，因为异常粒度太粗了。

如果业务需要细粒度的异常码以及异常描述，我们可以选择自己仿照着写一个属于自己的自定义异常。

**第一步：**

定义好我们自定义异常的异常码，以及默认异常描述

ErrorCodeEnum.kt

```kotlin
/**
 * 异常枚举
 *
 * @author gcc
 */
enum class ErrorCodeEnum(val code: Int, val msg: String) {
    // ...其它的异常码
    
    /***************************自定义错误******************************/
    /** 文件上传失败 */
    ERR_FILE_UPLOAD_FAIL(8888, "文件上传失败")
    ;
}
```

**第二步：**

编写自定义异常

FileUploadFailException.kt

```kotlin
/**
 * 文件上传失败异常
 * 
 * 说明：
 * 自定义异常
 * @author gcc
 */
class FileUploadFailException: RuntimeException {

    var code: Int? = null

    /** 默认的异常描述 */
    constructor(): this(ErrorCodeEnum.ERR_FILE_UPLOAD_FAIL.msg)

    /** 默认异常码 */
    constructor(message: String): this(ErrorCodeEnum.ERR_FILE_UPLOAD_FAIL.code, message)

    constructor(code: Int, message: String) : super(message) {
        this.code = code
    }

    constructor(message: String, cause: Throwable) : this(ErrorCodeEnum.ERR_FILE_UPLOAD_FAIL.code, message, cause)

    constructor(code: Int, message: String, cause: Throwable) : super(message, cause) {
        this.code = code
    }
}
```

**第三步：**

全局异常处理器中拦截并处理该异常

GlobalExceptionHandler.kt

```kotlin
/**
 * 全局异常处理器
 *
 * @author gcc
 */
@RestControllerAdvice
class GlobalExceptionHandler {
    private val logger = LoggerFactory.getLogger(this::class.java)
    
    // ....其它的异常处理

    /**
     * 文件上传失败异常处理
     */
    @ExceptionHandler(FileUploadFailException::class)
    @ResponseStatus(HttpStatus.BAD_REQUEST)
    fun argumentExceptionHandler(ex: FileUploadFailException): ApiResult<*> {
        logger.error("抛出文件上传失败异常：", ex)
        return ApiResult.result(ex.code, ex.message, null)
    }
}
```



## 使用自定义的异常

自定义异常写完了，使用一下看看吧

SysFileController.kt
```kotlin
@Api(tags = ["系统文件"])
@PreAuth(replace = "sys:file")
@RestController
@RequestMapping("/api/system/file")
class SysFileController: SuperSimpleController<ISysFileService, SysFile>() {


    /**
     * 测试触发自定义异常
     */
    @GetMapping("/test")
    fun testThrowException(): ApiResult<Boolean> {
        throw FileUploadFailException("哎呀呀，文件上传失败了~~ 可能网络不好，请稍后再试")
    }

}
```

请求接口返回的结果为：
```json
{
  "code": 8888,
  "message": "哎呀呀，文件上传失败了~~ 可能网络不好，请稍后再试",
  "data": null,
  "error": null
}
```
